### ISSUE TITLE
After installation, the debug toolbar does not work

### ISSUE THREAD

**Issue by PunchyRascal** [symfony/website-skeleton#10]
After I tried tu run the application created via:

`composer create-project symfony/website-skeleton my-project`

I got some issues on the welcome page:

![image](https://user-images.githubusercontent.com/821272/41189954-38f4808a-6bd6-11e8-8423-533762caf112.png)

When I click on the "open profiler" link in the toolbar, I get plain 404 error page.
Running on PHP Version 7.2.6 with all settings okayed by the checker:

![image](https://user-images.githubusercontent.com/821272/41189963-7406ac8e-6bd6-11e8-8f54-a4c7fdf4c7d9.png)

**Comment by PunchyRascal** [comment]
Also I am not sure if maybe this should have been filed under the main repository.

**Comment by loevgaard** [comment]
After running that command, did it install Symfony 3.4? Arguably it should install 4.1.

**Comment by PunchyRascal** [comment]
I am at another machine now, but this is just after I ran that command, so apparently it did install 3.4.

**Comment by PunchyRascal** [comment]
So this was apparently due to missing .htaccess in my public folder as per
https://symfony.com/doc/current/setup/web_server_configuration.html
