### ISSUE TITLE
Warning: Ambiguous class resolution

### ISSUE THREAD

**Issue by melicerte** [symfony/website-skeleton#225]
Hi, I'm not sure if it's the right place to set this issue, please tell me if I'm wrong.

After installing  
`composer create-project symfony/website-skeleton my-project`

then dump autoload
`composer dump-autoload -o`

I get those warnings about contracts (full warnings in file
[warning.log](https://github.com/symfony/website-skeleton/files/3286131/warning.log)
) :
```
Warning: Ambiguous class resolution, "Symfony\Contracts\HttpClient\ResponseStreamInterface" was found in both "/var/www/ffcc/vendor/symfony/http-client-contracts/ResponseStreamInterface.php" and "/var/www/ffcc/vendor/symfony/contracts/HttpClient/ResponseStreamInterface.php", the first will be used.
```

**Comment by nicolas-grekas** [comment]
Thanks, fixed in #227
