### ISSUE TITLE
Monolog config issue in prod environment with symfony 3.4

### ISSUE THREAD

**Issue by mdevlamynck** [symfony/website-skeleton#232]
With a project freshly created with `composer create-project symfony/website-skeleton my-project` there is an issue with the Monolog configuration in prod environment.

When you run a `bin/console c:c --env=prod` you get:
```
In MonologExtension.php line 329:
  "excluded_http_codes" cannot be used as your version of Monolog bridge does not support it.
```

Looking at https://github.com/symfony/monolog-bundle/blob/v3.3.1/DependencyInjection/MonologExtension.php#L328, it seems to be caused by the indirect dependency on symfony/monolog-bridge ^4.1 (looking at the releases, `HttpCodeActivationStrategy` was introduced in the 4.1.0 version). Since the `composer create-project` command installed symfony/monolog-brideg 3.4.28, the `excluded_http_codes` option is not supported.

**Comment by AienTech** [comment]
any solutions yet?

**Comment by AienTech** [comment]
a quick workaround would be to change the monolog bundle version to 3.1, as follow:
`"symfony/monolog-bundle": "3.1.0"`

**Comment by mfu-aroche** [comment]
Bump, same issue, i didn't test @AienTech workaround though.

**Comment by nicolas-grekas** [comment]
I don't think this is an issue anymore - recipes are using `excluded_http_codes` when 3.3 is installed.

**Comment by ianfoulds** [comment]
This is still an issue when using the 3.4 LTS website-skeleton. No action seems to be happening in issue [symfony/website-skeleton#639](https://github.com/symfony/recipes/issues/639), which is still open, to resolve it.

This is breaking my Travis CI testing when calling self::bootKernel().
