### ISSUE TITLE
Replace SwiftMailer by Symfony Mailer in master/5.0

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/website-skeleton#240]
Currently there is a SwiftMailer-related issue that prevents creating Symfony 5 apps with the website skeleton (see https://github.com/symfony/swiftmailer-bundle/pull/295).

However, shouldn't we replace `symfony/swiftmailer-bundle` by `symfony/mailer` in the `master` branch of this `website-skeleton`?

**Comment by fabpot** [comment]
I would even do it in 4.4.
