### ISSUE TITLE
No bin folder created when running composer create-project symfony/website-skeleton

### ISSUE THREAD

**Issue by atillay** [symfony/website-skeleton#249]
Hello,

I created a new project with the command `composer create-project symfony/website-skeleton` but the installation fails (bin directory does not get created) : 
```
Script cache:clear returned with error code 1
Could not open input file: ./bin/console
```

I tried with the command `composer create-project symfony/skeleton` and it works.  

Then I copied the bin directory to the project created with symfony/website-skeleton but I still get an error : 
```
The parameter "doctrine_migrations.dir_name" has a dependency on a non-existent parameter "kernel.root_dir". 
Did you mean one of these: "kernel.project_dir", "kernel.cache_dir", "kernel.logs_dir"?     
```

I'm using PHP 7.3.9.

**Comment by atillay** [comment]
It seems some recipes are not well executed.
Temporary fix : `$ composer sync-recipes --force`

**Comment by corriol** [comment]
Hi,

I have the same issue with symfony new project_dir --full.

**Comment by fabpot** [comment]
Should be fixed by https://github.com/symfony/recipes/pull/732
