### ISSUE TITLE
Install specific Symfony version

### ISSUE THREAD

**Issue by aleixfabra** [symfony/website-skeleton#30]
How can I install Symfony 4.0?

If I specific the `4.0` version it installs Symfony `4.1.1` ....

<img width="639" alt="captura de pantalla 2018-07-20 a las 13 01 26" src="https://user-images.githubusercontent.com/6033142/42999173-093d385c-8c1d-11e8-8e2f-d1c11ee9c0be.png">

<img width="499" alt="captura de pantalla 2018-07-20 a las 13 04 09" src="https://user-images.githubusercontent.com/6033142/42999274-6a72cb82-8c1d-11e8-870c-aaf7dec2b903.png">

Any help please?

**Comment by nicolas-grekas** [comment]
If you really want to stick to one minor version (why would you do so?), you need to change the version requirements in the composer.json file (e.g. using ~4.0.0 instead of ~4.0).
I'm closing here since we use github for bug fixes only. Cheers.
