### ISSUE TITLE
Unrecognized option "validator" under "framework"

### ISSUE THREAD

**Issue by aplab** [symfony/website-skeleton#42]
Composer version 1.6.5
linux debian 9.4
PHP 7.2.7-1stretch~1.gbpfd8e2e (cli)

run: composer create-project symfony/website-skeleton my-project

returns error

> 
```
Executing script cache:clear [KO]
 [KO]
Script cache:clear returned with error code 1
!!  
!!  In ArrayNode.php line 311:
!!                                                       
!!    Unrecognized option "validator" under "framework"  
!!                                                       
!!  
!!  
Script @auto-scripts was called via post-install-cmd
```

**Comment by skynetweb** [comment]
Hmm, i have the same issue but i fixed it by commenting the file content of  validator.yaml from config/packages i don't know why but after that it worked. I'm pretty sure this is not a valid fix

**Comment by nicolas-grekas** [comment]
Fixed by https://github.com/symfony/recipes/pull/445
Please retry.

**Comment by aplab** [comment]
Thanks! All works fine!
