### ISSUE TITLE
ext-ctype is a dependency in skeleton but not website-skeleton

### ISSUE THREAD

**Issue by msheakoski** [symfony/website-skeleton#60]
Since website-skeleton "extends" skeleton, shouldn't ext-ctype and symfony/polyfill-ctype also be dependencies in here? symfony/skeleton#62

**Comment by nicolas-grekas** [comment]
Correct, would you like to send a PR on branch 3.4?

**Comment by msheakoski** [comment]
Here you go! #61 Is the composer.lock automatically generated by the bot?
