### ISSUE TITLE
Creating a new project website-skeleton assets not symbolic linked

### ISSUE THREAD

**Issue by lerminou** [symfony/website-skeleton#68]
When running the installer command to create a new project : 
 **composer create-project symfony/website-skeleton my-project**

At the end, the following auto-scripts are created:
```
        "auto-scripts": {
            "cache:clear": "symfony-cmd",
            "assets:install %PUBLIC_DIR%": "symfony-cmd"
        },
```

Should the _asset:install_ command have the parameters **--symlink** as marked best practice in a old blog post https://symfony.com/blog/new-in-symfony-2-6-smarter-assets-install-command

**Comment by nicolas-grekas** [comment]
Would you mind sending a PR to propose your change on https://github.com/symfony/recipes/blob/master/symfony/framework-bundle/3.3/manifest.json?

**Comment by lerminou** [comment]
Well, i see the issue which remove these options:
https://github.com/symfony/recipes/issues/398
I don't know what is better, maybe just inform users to modify themself the composer.json is they want symlink which is no more by default?

or revert the PR already merged to follow the best practices ?

**Comment by nicolas-grekas** [comment]
Thanks for the link. I think having a default that works for most people is the most important, thus we shouldn't change as the arguments in the issues are good ones. Which means adding `--symlink` is not a universal best practice. Not sure where we should add it if we need to.

**Comment by lerminou** [comment]
I'm ok with this, it needs to work for most people. I will close this issue.
