### ISSUE TITLE
The skeleton install stale dependencies by default

### ISSUE THREAD

**Issue by dunglas** [symfony/website-skeleton#85]
By default, stale dependencies are installed, `composer update` must be executed after the install to fix the problem.

Example:

    composer create-project symfony/website-skeleton test-website-skeleton
    cd test-website-skeleton
    composer info symfony/test-pack
    > versions : * v1.0.2
    composer update
    > snip
    > - Updating symfony/test-pack (v1.0.2 => v1.0.3): Loading from cache
    > - Updating ocramius/proxy-manager (2.1.1 => 2.2.1): Downloading (100%)

**Comment by nicolas-grekas** [comment]
Correct, that's because PHP 7.1 is used to resolve the deps. That's expected.
